spring:
  application:
    name: single-message-consumer

  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      groupId: consumer-group-${spring.application.name}
