version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka_1:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka_1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"

  kafka_2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka_2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_2:39093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9093"
      - "39093:39093"

  producer:
    build:
      context: /producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - kafka_1
      - kafka_2
    environment:
      BOOTSTRAP_SERVERS: kafka_1:29092,kafka_2:39093
    restart: unless-stopped

  batch-message-consumer:
    build:
      context: /batch-message-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka_1
      - kafka_2
      - producer
    environment:
      BOOTSTRAP_SERVERS: kafka_1:29092,kafka_2:39093
    restart: unless-stopped
    deploy:
      replicas: 2

  single-message-consumer:
    build:
      context: /single-message-consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka_1
      - kafka_2
      - producer
    environment:
      BOOTSTRAP_SERVERS: kafka_1:29092,kafka_2:39093
    restart: unless-stopped
    deploy:
      replicas: 2