spring:
  application:
    name: batch-message-consumer   # Название приложения

  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}   # Адреса серверов kafka
      enable-auto-commit: false                 # Автокоммит отключен
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest                          # Чтение из топика начинается с самой старой записи
      groupId: consumer-group-${spring.application.name}   # group-id содержит имя приложения для уникальности
      max-poll-records: 10                                 # Максимальное количество сообщений, которое нужно вычитать за раз
      fetch-min-size: 2048                                 # 2 мб минимальный размер пакета
      fetch-max-wait: 100                                  # 100 мс максимальное время ожидания
      properties:
        spring:
          json:
            trusted:
              packages: "*"                                # Разрешить десериализовывать объекты из любых пакетов